version: '2'
services:
  sunrisewebsocketapp-app:
    image: sunrisewebsocketapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://sunrisewebsocketapp-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=sunrisewebsocketapp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 9700:9700
  sunrisewebsocketapp-mongodb:
    extends:
      file: mongodb.yml
      service: sunrisewebsocketapp-mongodb
